import type {
  TeamPersona,
  Lead,
  WorkflowSOP,
  WorkLink,
  ProblemItem,
  VisualDiagram,
  TeamNote,
  TeamTask,
} from './team-types';

export const INITIAL_PERSONAS: TeamPersona[] = [
  {
    id: 'tp-tech',
    name: 'Deepak (Tech Lead)',
    role: 'Tech Lead',
    initials: 'DL',
    color: 'emerald',
    email: 'deepak@dingdong.app',
    phone: '+91 98765 00001',
  },
  {
    id: 'tp-bizdev',
    name: 'Partner 1 (BizDev)',
    role: 'BizDev Partner',
    initials: 'BP',
    color: 'blue',
    email: 'bizdev@dingdong.app',
    phone: '+91 98765 00002',
  },
  {
    id: 'tp-ops',
    name: 'Partner 2 (Operations)',
    role: 'Operations Partner',
    initials: 'OP',
    color: 'amber',
    email: 'ops@dingdong.app',
    phone: '+91 98765 00003',
  },
];

export interface TeamMissionItem {
  id: string;
  title: string;
  description: string;
  iconName: string;
  color: string;
  objective: string;
  why_it_matters: string;
  definition_of_success: string;
  customer_segment?: string;
  revenue_model?: string;
  status: 'active' | 'on_hold' | 'completed';
  is_pinned: boolean;
  target_date: string;
  tags: string[];
}

export const INITIAL_TEAM_MISSIONS: TeamMissionItem[] = [
  {
    id: 'm-turf',
    title: 'TurfSlot Arena',
    description: 'Instant turf booking & team split-bill platform for sports arenas',
    iconName: 'Activity',
    color: 'emerald',
    objective: 'Eliminate no-shows and automate upfront player split payments for 5 local turfs',
    why_it_matters: 'Turf owners lose 20-30% of revenue from weekend no-shows and WhatsApp chaos',
    definition_of_success: '3 paying venues live on the platform with 50+ weekly online bookings',
    customer_segment: 'Independent turf and sports-arena owners managing bookings through calls and WhatsApp',
    revenue_model: 'Monthly venue subscription, plus a small fee on completed bookings. Premium split-payments, scoreboards, and retention tools expand revenue per venue.',
    status: 'active',
    is_pinned: true,
    target_date: '2026-09-15',
    tags: ['Sports', 'B2B2C', 'P0-Priority', 'High-Cashflow'],
  },
  {
    id: 'm-gym',
    title: 'GymFlow OS',
    description: 'Smart member attendance, slot capacity & automated fee renewals for gyms',
    iconName: 'Dumbbell',
    color: 'blue',
    objective: 'Automate WhatsApp fee renewals and member QR check-ins for boutique gyms',
    why_it_matters: 'Manual fee chasing causes 15% revenue leakage and awkward member conversations',
    definition_of_success: '2 gyms using automated QR check-in & UPI fee renewal reminders',
    customer_segment: 'Boutique gym owners who manually manage attendance, renewals, and member follow-ups',
    revenue_model: 'Recurring software subscription per gym, supported by paid onboarding and premium member-engagement or payment automation add-ons.',
    status: 'active',
    is_pinned: true,
    target_date: '2026-09-20',
    tags: ['Fitness', 'SaaS', 'P0-Priority', 'Recurring-MRR'],
  },
  {
    id: 'm-deals',
    title: 'FlashLocal Deals',
    description: 'Hyperlocal flash discounts driving footfall during off-peak hours',
    iconName: 'Tag',
    color: 'amber',
    objective: 'Help cafes and boutiques fill empty tables/hours with 2-hour flash vouchers',
    why_it_matters: 'Off-peak hours (2-5 PM) are pure loss for local retail with fixed overheads',
    definition_of_success: '10 cafes publishing weekly flash vouchers with 100+ QR redemptions',
    customer_segment: 'Local cafes, restaurants, and retailers with unused off-peak capacity',
    revenue_model: 'Merchant subscription for campaign tools, with a performance fee on redeemed offers and paid placement for higher local visibility.',
    status: 'active',
    is_pinned: false,
    target_date: '2026-09-30',
    tags: ['Retail', 'Dining', 'P1-Priority', 'Marketplace'],
  },
  {
    id: 'm-seasonal',
    title: 'PopUp Radar',
    description: 'Interactive map for seasonal festive stalls, artisan fairs & organic pop-ups',
    iconName: 'Compass',
    color: 'purple',
    objective: 'Enable temporary festive vendors to gain instant local discovery and pre-orders',
    why_it_matters: 'Pop-ups run for only 2-4 weeks and have zero digital marketing presence',
    definition_of_success: '20 seasonal stalls mapped with 500+ customer route navigations',
    customer_segment: 'Short-lived festive vendors, pop-up operators, and local event organizers',
    revenue_model: 'Vendor listing plans, promoted placement, and a transaction fee on pre-orders, with event-organizer packages as an expansion path.',
    status: 'active',
    is_pinned: false,
    target_date: '2026-10-15',
    tags: ['Events', 'Pop-ups', 'P2-Seasonal', 'Discovery'],
  },
];

export const INITIAL_LEADS: Lead[] = [
  {
    id: 'lead-1',
    missionId: 'm-turf',
    businessName: 'Champions Arena (7-a-Side & Cricket)',
    category: 'Turf',
    ownerName: 'Rajesh Kumar',
    phone: '9876543210',
    location: 'Indiranagar 100ft Rd',
    status: 'active_pilot',
    notes: 'Has 2 football turfs and 1 cricket net. Struggles with Friday/Saturday last-minute cancellations.',
    nextFollowUp: '2026-08-22',
    pilotStartDate: '2026-08-15',
    pilotEndDate: '2026-08-29',
    monthlyValue: 2499,
    createdBy: 'Partner 1 (BizDev)',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-2',
    missionId: 'm-gym',
    businessName: 'IronPeak Fitness & CrossFit',
    category: 'Gym',
    ownerName: 'Vikram Reddy',
    phone: '9876543211',
    location: 'Koramangala 4th Block',
    status: 'meeting_set',
    notes: '280 active members. Uses paper register for check-in. Excited about automated WhatsApp renewal alerts.',
    nextFollowUp: '2026-08-20',
    monthlyValue: 3499,
    createdBy: 'Partner 1 (BizDev)',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-3',
    missionId: 'm-turf',
    businessName: 'GreenPitch Astro Park',
    category: 'Turf',
    ownerName: 'Syed Farhan',
    phone: '9876543212',
    location: 'HSR Layout Sector 2',
    status: 'contacted',
    notes: 'Needs demo on WhatsApp group link generation for player split payments.',
    nextFollowUp: '2026-08-21',
    createdBy: 'Partner 1 (BizDev)',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-4',
    missionId: 'm-deals',
    businessName: 'BrewHouse Specialty Cafe',
    category: 'Retail',
    ownerName: 'Ananya Roy',
    phone: '9876543213',
    location: 'Indiranagar 12th Main',
    status: 'new',
    notes: 'Looking to boost customer footfall between 3 PM and 6 PM on weekdays.',
    nextFollowUp: '2026-08-23',
    createdBy: 'Deepak (Tech Lead)',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'lead-5',
    missionId: 'm-seasonal',
    businessName: 'The Organic Clay Studio',
    category: 'Seasonal',
    ownerName: 'Meera Nambiar',
    phone: '9876543214',
    location: 'Whitefield Main Road',
    status: 'active_pilot',
    notes: 'Running a 3-week festive handmade ceramic pottery stall.',
    nextFollowUp: '2026-08-25',
    pilotStartDate: '2026-08-18',
    pilotEndDate: '2026-09-08',
    monthlyValue: 1200,
    createdBy: 'Partner 2 (Operations)',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_WORKFLOWS: WorkflowSOP[] = [
  {
    id: 'sop-turf-onboard',
    missionId: 'm-turf',
    title: 'Turf Venue 14-Day Free Pilot SOP',
    description: 'Guaranteed 5-step onboarding protocol to convert turf owners without technical friction.',
    targetOutcome: '3 live turf bookings done via automated split-UPI link within 72 hours.',
    status: 'in_progress',
    steps: [
      {
        id: 's1',
        stepNumber: 1,
        title: 'Field Visit & WhatsApp Audit',
        description: 'Visit venue, inspect existing paper register / WhatsApp group, note slot prices.',
        completed: true,
        completedAt: '2026-08-16',
        completedBy: 'Partner 1 (BizDev)',
      },
      {
        id: 's2',
        stepNumber: 2,
        title: 'Configure Slot Grid & Split UPI',
        description: 'Enter hourly slots into TurfSlot and connect turf owner UPI VPA for direct settlement.',
        completed: true,
        completedAt: '2026-08-17',
        completedBy: 'Deepak (Tech Lead)',
      },
      {
        id: 's3',
        stepNumber: 3,
        title: 'Generate Printable QR Table Stand',
        description: 'Provide 2 acrylic counter QR stands and captain WhatsApp forward templates.',
        completed: false,
        requiredProof: 'Photo of acrylic stand on counter',
      },
      {
        id: 's4',
        stepNumber: 4,
        title: 'First Weekend Live Pilot Observation',
        description: 'Stand by during Friday 6-10 PM peak bookings to assist desk staff.',
        completed: false,
      },
      {
        id: 's5',
        stepNumber: 5,
        title: 'Pilot Review & Paid Plan Conversion',
        description: 'Present summary of zero no-shows and advance fees collected; collect subscription.',
        completed: false,
      },
    ],
  },
  {
    id: 'sop-gym-onboard',
    missionId: 'm-gym',
    title: 'Gym QR Check-In & Fee Reminder SOP',
    description: 'Rollout automated member check-in without buying expensive biometric hardware.',
    targetOutcome: '100% daily check-ins logged via QR code and zero manual WhatsApp fee messages.',
    status: 'in_progress',
    steps: [
      {
        id: 'g1',
        stepNumber: 1,
        title: 'Member CSV Import',
        description: 'Import member name, phone number, plan expiration date from Excel.',
        completed: true,
        completedAt: '2026-08-16',
        completedBy: 'Deepak (Tech Lead)',
      },
      {
        id: 'g2',
        stepNumber: 2,
        title: 'Front-Desk QR Deployment',
        description: 'Place laminated QR sticker at entrance for instant smartphone scan.',
        completed: true,
        completedAt: '2026-08-17',
        completedBy: 'Partner 2 (Operations)',
      },
      {
        id: 'g3',
        stepNumber: 3,
        title: 'Auto-WhatsApp Daemon Verification',
        description: 'Send test 3-day expiry reminder with direct UPI payment link to test number.',
        completed: false,
      },
      {
        id: 'g4',
        stepNumber: 4,
        title: 'Owner Weekly Digest Setup',
        description: 'Deliver weekly WhatsApp summary of renewals collected and expired members.',
        completed: false,
      },
    ],
  },
];

export const INITIAL_WORK_LINKS: WorkLink[] = [
  {
    id: 'wl-1',
    missionId: 'm-turf',
    title: 'Live Mobile Booking & Split Prototype',
    url: 'https://turfslot.app/demo/indiranagar',
    category: 'demo',
    description: 'Fast mobile view for team captains to book and split payment.',
    addedBy: 'Deepak (Tech Lead)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wl-2',
    missionId: 'm-turf',
    title: 'TurfSlot Arena GitHub Repository',
    url: 'https://github.com/syncatch/turfslot-core',
    category: 'repo',
    description: 'Next.js 14 + Tailwind + Supabase Postgres schema and UPI webhooks.',
    addedBy: 'Deepak (Tech Lead)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wl-3',
    missionId: 'm-gym',
    title: 'GymFlow Attendance Web App',
    url: 'https://gymflow.app/ironpeak',
    category: 'demo',
    description: 'Front desk scanner and crowd density live view.',
    addedBy: 'Deepak (Tech Lead)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'wl-4',
    missionId: 'm-turf',
    title: 'Pitch Deck & 1-Pager for Owners',
    url: 'https://syncatch.app/docs/turfslot-onepager.pdf',
    category: 'doc',
    description: 'Calculates lost revenue from no-shows and explains 14-day zero-risk trial.',
    addedBy: 'Partner 1 (BizDev)',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_PROBLEMS: ProblemItem[] = [
  {
    id: 'prob-1',
    missionId: 'm-turf',
    audienceCategory: 'Turf Owner',
    title: 'Owner reluctant to change from personal UPI QR',
    description: 'Owner fears payments will be delayed if routed through a platform account instead of directly to their personal Google Pay.',
    source: 'Indiranagar Arena Visit',
    severity: 'blocker',
    status: 'solved',
    tags: ['UPI', 'Instant-Settlement', 'Trust'],
    loggedBy: 'Partner 1 (BizDev)',
    createdAt: new Date().toISOString(),
    solvedNotes: 'Configured direct peer-to-peer UPI intent with owner VPA as direct payee so funds hit their bank instantly without holding account.',
  },
  {
    id: 'prob-2',
    missionId: 'm-turf',
    audienceCategory: 'Player / Captain',
    title: 'Last 2 players delay payment during 10-minute hold window',
    description: 'If 6 out of 8 players pay but 2 are unresponsive, slot reservation expires and captain gets frustrated.',
    source: 'Weekend Playtest Session',
    severity: 'friction',
    status: 'investigating',
    tags: ['Payment-Timeout', 'UX', 'Split-Logic'],
    loggedBy: 'Deepak (Tech Lead)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prob-3',
    missionId: 'm-gym',
    audienceCategory: 'Gym Owner',
    title: 'Members forget to check in if queue forms at front desk',
    description: 'During 7 AM morning rush, bottleneck occurs if multiple members scan single QR code on counter.',
    source: 'IronPeak Morning Audit',
    severity: 'friction',
    status: 'open',
    tags: ['Check-In-Friction', 'Peak-Hours'],
    loggedBy: 'Partner 2 (Operations)',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'prob-4',
    missionId: 'm-deals',
    audienceCategory: 'Cafe Manager',
    title: 'Staff forgets to validate 2-hour discount timer on vouchers',
    description: 'Customers screenshot expired vouchers and present them at cash counter.',
    source: 'BrewHouse Pilot Interview',
    severity: 'blocker',
    status: 'open',
    tags: ['Fraud-Prevention', 'Voucher-Validation'],
    loggedBy: 'Partner 2 (Operations)',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_TEAM_NOTES: TeamNote[] = [
  {
    id: 'tn-1',
    missionId: 'm-turf',
    title: 'Pitch Script & Objection Handling for Turf Owners',
    category: 'Playbook',
    pinned: true,
    author: 'Partner 1 (BizDev)',
    content: `# Turf Owner 3-Minute Pitch Script

1. **The Hook**: "How many slots got cancelled last-minute this Friday? If even one slot goes empty, that is ₹1,500 gone forever."
2. **The Solution**: "TurfSlot gives your players a 1-click link where all 10 players pay their ₹150 share via UPI before the slot is confirmed. Zero advance chasing for your staff."
3. **Direct Money Flow**: "Payments go directly into your existing GooglePay/PhonePe UPI account in real-time. We never hold your funds."
4. **The Offer**: "14 days completely free. If we don't save you at least 3 cancelled slots, you owe us nothing."`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tn-2',
    missionId: 'm-gym',
    title: 'GymFlow Hardwareless Check-In Architecture',
    category: 'Strategy',
    pinned: true,
    author: 'Deepak (Tech Lead)',
    content: `# GymFlow Technical Overview

- **Zero Biometrics Needed**: Uses high-entropy dynamic QR rotation on a small tablet or laminated stand.
- **WhatsApp Daemon**: Node cron worker inspects Postgres expiring members daily at 09:00 AM and triggers personalized renewal links.
- **Instant UPI DeepLink**: Pre-populates amount and plan name so member completes renewal in 2 taps.`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'tn-3',
    missionId: 'm-turf',
    title: 'Indiranagar & HSR Field Visit Debrief',
    category: 'Field Intel',
    pinned: false,
    author: 'Partner 2 (Operations)',
    content: `# Field Visit Notes — August 2026

- **Indiranagar Champions Arena**: Owner Rajesh is receptive. Wants cricket bowling machine integration in phase 2.
- **GreenPitch HSR**: Staff uses paper diary. Manager needs a 5-minute training on how to verify online bookings on the tablet.
- **Action Item**: Bring printed A5 acrylic stands for counter on Wednesday.`,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const INITIAL_TEAM_TASKS: TeamTask[] = [
  {
    id: 'tt-1',
    missionId: 'm-turf',
    title: 'Deliver 2x acrylic QR stands to Champions Arena',
    outcome: 'Stands placed on Indiranagar counter with QR live',
    status: 'in_progress',
    priority: 'critical',
    assigneeRole: 'Operations Partner',
    dueDate: '2026-08-20',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tt-2',
    missionId: 'm-turf',
    title: 'Implement UPI Webhook auto-confirmation fallback',
    outcome: 'Auto-verify pending split payments when bank confirmation is delayed',
    status: 'in_progress',
    priority: 'high',
    assigneeRole: 'Tech Lead',
    dueDate: '2026-08-21',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tt-3',
    missionId: 'm-gym',
    title: 'Audit member CSV import for IronPeak Gym',
    outcome: 'All 280 members loaded with active plan expiry dates',
    status: 'done',
    priority: 'high',
    assigneeRole: 'Tech Lead',
    dueDate: '2026-08-17',
    createdAt: new Date().toISOString(),
    completedAt: '2026-08-17',
  },
  {
    id: 'tt-4',
    missionId: 'm-gym',
    title: 'Conduct on-site front desk training for IronPeak manager',
    outcome: 'Manager comfortably checks in members and handles renewal status',
    status: 'backlog',
    priority: 'normal',
    assigneeRole: 'Operations Partner',
    dueDate: '2026-08-22',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'tt-5',
    missionId: 'm-deals',
    title: 'Design 2-hour dynamic countdown badge for BrewHouse vouchers',
    outcome: 'Voucher renders animated expiration clock preventing screenshot reuse',
    status: 'backlog',
    priority: 'critical',
    assigneeRole: 'Tech Lead',
    dueDate: '2026-08-24',
    createdAt: new Date().toISOString(),
  },
];

export const INITIAL_DIAGRAMS: VisualDiagram[] = [
  {
    id: 'diag-turf-flow',
    missionId: 'm-turf',
    title: 'Turf Booking & Split-Bill Architecture Flow',
    description: 'End-to-end player booking journey, payment split locking, and turf tablet sync.',
    diagramType: 'user_journey',
    updatedAt: new Date().toISOString(),
    nodes: [
      { id: 'n-player', label: 'Team Captain', sublabel: 'Opens mobile booking link', type: 'actor', x: 40, y: 60, color: 'emerald', icon: 'User' },
      { id: 'n-slots', label: 'Live Slot Grid', sublabel: 'Locks 7:00 PM - 8:00 PM slot for 10m', type: 'process', x: 280, y: 60, color: 'blue', icon: 'Calendar' },
      { id: 'n-split', label: 'Split-UPI Generator', sublabel: 'Creates 8x ₹250 instant UPI links', type: 'system', x: 520, y: 60, color: 'purple', icon: 'CreditCard' },
      { id: 'n-gateway', label: 'UPI Auto-Reconciliation', sublabel: 'Verifies 100% payments collected', type: 'database', x: 520, y: 220, color: 'amber', icon: 'CheckCircle' },
      { id: 'n-owner', label: 'Turf Tablet Dashboard', sublabel: 'Live buzzer + WhatsApp confirmation', type: 'actor', x: 280, y: 220, color: 'emerald', icon: 'Smartphone' },
    ],
    edges: [
      { id: 'e1', from: 'n-player', to: 'n-slots', label: 'Selects Slot & Pitch' },
      { id: 'e2', from: 'n-slots', to: 'n-split', label: 'Splits with 8 players' },
      { id: 'e3', from: 'n-split', to: 'n-gateway', label: 'Teammates Pay via UPI' },
      { id: 'e4', from: 'n-gateway', to: 'n-owner', label: 'Confirmed & Advance Locked' },
    ],
  },
  {
    id: 'diag-gym-flow',
    missionId: 'm-gym',
    title: 'GymFlow Automated Attendance & Fee Renewal Architecture',
    description: 'QR attendance flow, crowd density calculation, and WhatsApp auto-renewal loop.',
    diagramType: 'system_arch',
    updatedAt: new Date().toISOString(),
    nodes: [
      { id: 'g-member', label: 'Gym Member', sublabel: 'Scans front-desk QR code', type: 'actor', x: 40, y: 60, color: 'blue', icon: 'User' },
      { id: 'g-density', label: 'Crowd Meter', sublabel: 'Updates live capacity (e.g. 24/40)', type: 'system', x: 280, y: 60, color: 'emerald', icon: 'Activity' },
      { id: 'g-expiry', label: 'Expiry Daemon', sublabel: 'Checks days until plan expiration', type: 'database', x: 520, y: 60, color: 'purple', icon: 'Clock' },
      { id: 'g-whatsapp', label: 'WhatsApp Bot', sublabel: 'Sends 1-click UPI renewal message', type: 'process', x: 520, y: 220, color: 'emerald', icon: 'MessageCircle' },
      { id: 'g-desk', label: 'Front Desk Portal', sublabel: 'Instant receipt & member lookup', type: 'actor', x: 280, y: 220, color: 'blue', icon: 'Monitor' },
    ],
    edges: [
      { id: 'ge1', from: 'g-member', to: 'g-density', label: 'Check-in scan' },
      { id: 'ge2', from: 'g-density', to: 'g-expiry', label: 'Verify active plan' },
      { id: 'ge3', from: 'g-expiry', to: 'g-whatsapp', label: 'Trigger 3 days before' },
      { id: 'ge4', from: 'g-whatsapp', to: 'g-desk', label: 'Renewal synced' },
    ],
  },
];
